### ISSUE TITLE
Replacement of joke2/Faker with russellgill/ArtemisFaker

### ISSUE THREAD

**Issue by russellgill** [artemis-analytics/dolos#3]
Replacement of existing Faker module with custom faker module. Currently constructing the shim to allow seamless integration of the package with Dolos. This will allow it to behave mostly as a drop-in replacement. As of now, ArtemisFaker is missing some elements that dolos makes use of in Faker. These are being integrated into the shim layer that is being constructed. This Artemis Faker package is internal and not is an external dependency.

**Comment by ryanmwhitephd** [comment]
@russellgill can we document your work? 
I see two development branches for migrating the script-based Faker. One depends directly on your personal ArtemisFaker repo, I believe. This looks to be the primary branch now for merging the two projects together.

**Comment by russellgill** [comment]
@ryanmwhitephd Sure thing. I've documented my ArtemisFaker in the repo, however I'll start working up some docs on what I have here now.

**Comment by ryanmwhitephd** [comment]
- Include unit tests for ArtemisFaker.
- If possible, ensure existing simutable tests run. Requires re-defining the Faker provider classes for "name", "Ean", etc...

Other follow-up
- Investigate use of scipy.stats or numpy.random rather than using a configuration file (yaml) which defines a string for configuring the engine.

**Comment by russellgill** [comment]
@ryanmwhitephd Tests pass save for the ```test_simutable.py```. This test fails with the following (partial) stack-trace:

```
Traceback (most recent call last):
  File "test_synthesizer.py", line 262, in test_xmodifer
    protorows.append(s2.generate())
  File "/home/terminal/.local/lib/python3.7/site-packages/dolos/simutable/synthesizer.py", line 345, in generate
    darr = self.generate_original()
  File "/home/terminal/.local/lib/python3.7/site-packages/dolos/simutable/synthesizer.py", line 282, in generate_original
    self.generator_fcns[fake][0], params=None)  # Create fake datum
  File "/home/terminal/.local/lib/python3.7/site-packages/dolos/ArtemisFaker/Faker.py", line 66, in fake
    raise KeyError("Faker %s method not available." %method)
KeyError: 'Faker  method not available
```
Based on this, integration is completed -- that being said, until we replace the methods in ```test_simulator.py``` with either Numpy ones, or we create them from scratch, this test will fail. In the mean-time, I'll write some stub classes to take the place of those generators.
